### ISSUE TITLE
polyfill.io transfer of ownership

### ISSUE THREAD

**Issue by ob6160** [guardian/gateway#2597]
There has been a recent development around polyfill.io which I believe is used across several projects in places such as https://github.com/guardian/gateway/blob/c57fa76220b9e972d5fc52d85388d38a8adde5c4/scripts/okta/okta-login.html#L12

[Polyfill.io](http://polyfill.io/) recently transferred over to a Chinese company called Funnull meaning that hosting for the service has [probably](https://github.com/polyfillpolyfill/polyfill-service/issues/2834#issuecomment-1966346994) moved out of the UK/EU.

There's an active issue thread around this here: https://github.com/polyfillpolyfill/polyfill-service/issues/2834 

@coldlink

**Comment by coldlink** [comment]
Thanks for bringing this to our attention, thankfully Fastly already informed us, and we're using https://polyfill-fastly.io/ now!

**Comment by ob6160** [comment]
👏

**Comment by bo-rik** [comment]
Hi @coldlink. We're encountering issues since the move as well. Do you know who owns & hosts https://polyfill-fastly.io
Is it reliable to use in a production environment?

Thx!

**Comment by henrik** [comment]
@coldlink Could you please say more about how Fastly informed you? I noted in https://github.com/polyfillpolyfill/polyfill-service/issues/2834#issuecomment-1968622535 that I haven't found anything to clearly show that they run it.

**Comment by coldlink** [comment]
I had to delete my earlier post, but it's now been officially announced. https://community.fastly.com/t/new-options-for-polyfill-io-users/2540
